/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metodologia;

/**
 *
 * @author Usuario
 */
public class Ejercicio6 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio6
     */
    public Ejercicio6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiNombre = new javax.swing.JLabel();
        btnEsquina = new javax.swing.JButton();
        btnCentro = new javax.swing.JButton();
        btnAgrandar = new javax.swing.JButton();
        btnAchicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiNombre.setText("Juárez Lucas Edson Rubén");
        etiNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        etiNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnEsquina.setText("Esquina");
        btnEsquina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEsquinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEsquinaMouseExited(evt);
            }
        });
        btnEsquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsquinaActionPerformed(evt);
            }
        });

        btnCentro.setText("Centro");
        btnCentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCentroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCentroMouseExited(evt);
            }
        });
        btnCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentroActionPerformed(evt);
            }
        });

        btnAgrandar.setText("Agrandar");
        btnAgrandar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgrandarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgrandarMouseExited(evt);
            }
        });
        btnAgrandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrandarActionPerformed(evt);
            }
        });

        btnAchicar.setText("Achicar");
        btnAchicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAchicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAchicarMouseExited(evt);
            }
        });
        btnAchicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAchicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEsquina)
                .addGap(18, 18, 18)
                .addComponent(btnCentro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnAgrandar)
                .addGap(18, 18, 18)
                .addComponent(btnAchicar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(etiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(etiNombre)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEsquina)
                    .addComponent(btnCentro)
                    .addComponent(btnAgrandar)
                    .addComponent(btnAchicar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsquinaActionPerformed
        // TODO add your handling code here:
        etiNombre.setLocation(0, 0 );
    }//GEN-LAST:event_btnEsquinaActionPerformed
    private void btnCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroActionPerformed
        // TODO add your handling code here:
        etiNombre.setLocation(122, 100);
    }//GEN-LAST:event_btnCentroActionPerformed
    private void btnAgrandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrandarActionPerformed
        // TODO add your handling code here:
        etiNombre.setSize(etiNombre.getWidth()+2,etiNombre.getHeight()+2);
    }//GEN-LAST:event_btnAgrandarActionPerformed
    private void btnAchicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAchicarActionPerformed
        // TODO add your handling code here:
        etiNombre.setSize(etiNombre.getWidth()-2,etiNombre.getHeight()-2);
    }//GEN-LAST:event_btnAchicarActionPerformed
    private void btnEsquinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEsquinaMouseEntered
        // TODO add your handling code here:
        btnEsquina.setSize(btnEsquina.getWidth()+4, btnEsquina.getHeight()+4);        
    }//GEN-LAST:event_btnEsquinaMouseEntered
    private void btnCentroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentroMouseEntered
        // TODO add your handling code here:
        btnCentro.setSize(btnCentro.getWidth()+4, btnCentro.getHeight()+4);
    }//GEN-LAST:event_btnCentroMouseEntered
    private void btnAgrandarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgrandarMouseEntered
        // TODO add your handling code here:
        btnAgrandar.setSize(btnAgrandar.getWidth()+4, btnAgrandar.getHeight()+4);
    }//GEN-LAST:event_btnAgrandarMouseEntered
    private void btnAchicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAchicarMouseEntered
        // TODO add your handling code here:
        btnAchicar.setSize(btnAchicar.getWidth()+4, btnAchicar.getHeight()+4);
    }//GEN-LAST:event_btnAchicarMouseEntered
    private void btnEsquinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEsquinaMouseExited
        // TODO add your handling code here:
        btnEsquina.setSize(btnEsquina.getPreferredSize());
    }//GEN-LAST:event_btnEsquinaMouseExited
    private void btnCentroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentroMouseExited
        // TODO add your handling code here:
         btnCentro.setSize(btnCentro.getPreferredSize());
    }//GEN-LAST:event_btnCentroMouseExited
    private void btnAgrandarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgrandarMouseExited
        // TODO add your handling code here:
         btnAgrandar.setSize(btnAgrandar.getPreferredSize());
    }//GEN-LAST:event_btnAgrandarMouseExited
    private void btnAchicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAchicarMouseExited
        // TODO add your handling code here:
         btnAchicar.setSize(btnAchicar.getPreferredSize());
    }//GEN-LAST:event_btnAchicarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAchicar;
    private javax.swing.JButton btnAgrandar;
    private javax.swing.JButton btnCentro;
    private javax.swing.JButton btnEsquina;
    private javax.swing.JLabel etiNombre;
    // End of variables declaration//GEN-END:variables
}
