/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edjuarez.ejercicios1415y16;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Ejercicio15 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio15
     */
    public Ejercicio15() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        panelOficina1 = new javax.swing.JPanel();
        chkLP1 = new javax.swing.JCheckBox();
        chkLS1 = new javax.swing.JCheckBox();
        chkLsec1 = new javax.swing.JCheckBox();
        panelOficina2 = new javax.swing.JPanel();
        chkLP2 = new javax.swing.JCheckBox();
        chkLS2 = new javax.swing.JCheckBox();
        chkLsec2 = new javax.swing.JCheckBox();
        panelOficina3 = new javax.swing.JPanel();
        chkLP3 = new javax.swing.JCheckBox();
        chkLS3 = new javax.swing.JCheckBox();
        chkLsec3 = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        activacion = new javax.swing.JMenu();
        itemApagarTodas = new javax.swing.JMenuItem();
        MenuEncender = new javax.swing.JMenuItem();
        menuDia = new javax.swing.JMenu();
        itemOficina1D = new javax.swing.JMenuItem();
        itemOficina2D = new javax.swing.JMenuItem();
        itemOficina3D = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemTodasD = new javax.swing.JMenuItem();
        menuNoche = new javax.swing.JMenu();
        itemOficina1N = new javax.swing.JMenuItem();
        itemOficina2N = new javax.swing.JMenuItem();
        itemOficina3N = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemTodasN = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemSalir = new javax.swing.JMenuItem();
        Info = new javax.swing.JMenu();
        itemPrincipales = new javax.swing.JMenuItem();
        itemSecundarias = new javax.swing.JMenuItem();
        itemSeguridad = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemAcercade = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelOficina1.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficina 1"));

        chkLP1.setText("Luz Principal");

        chkLS1.setText("Luz Secundaria");

        chkLsec1.setText("Luz de Seguridad");

        javax.swing.GroupLayout panelOficina1Layout = new javax.swing.GroupLayout(panelOficina1);
        panelOficina1.setLayout(panelOficina1Layout);
        panelOficina1Layout.setHorizontalGroup(
            panelOficina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOficina1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelOficina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkLsec1)
                    .addComponent(chkLS1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkLP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        panelOficina1Layout.setVerticalGroup(
            panelOficina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOficina1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(chkLP1)
                .addGap(18, 18, 18)
                .addComponent(chkLS1)
                .addGap(18, 18, 18)
                .addComponent(chkLsec1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOficina2.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficina 2"));

        chkLP2.setText("LuzPrincipal");

        chkLS2.setText("Luz Secundaria");

        chkLsec2.setText("Luz de Seguridad");

        javax.swing.GroupLayout panelOficina2Layout = new javax.swing.GroupLayout(panelOficina2);
        panelOficina2.setLayout(panelOficina2Layout);
        panelOficina2Layout.setHorizontalGroup(
            panelOficina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOficina2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(panelOficina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkLsec2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkLP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkLS2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        panelOficina2Layout.setVerticalGroup(
            panelOficina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOficina2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(chkLP2)
                .addGap(18, 18, 18)
                .addComponent(chkLS2)
                .addGap(18, 18, 18)
                .addComponent(chkLsec2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOficina3.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficina 3"));

        chkLP3.setText("Luz Principal");

        chkLS3.setText("Luz Secundaria");

        chkLsec3.setText("Luz de Seguridad");

        javax.swing.GroupLayout panelOficina3Layout = new javax.swing.GroupLayout(panelOficina3);
        panelOficina3.setLayout(panelOficina3Layout);
        panelOficina3Layout.setHorizontalGroup(
            panelOficina3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOficina3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(panelOficina3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkLsec3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkLS3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkLP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        panelOficina3Layout.setVerticalGroup(
            panelOficina3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOficina3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(chkLP3)
                .addGap(18, 18, 18)
                .addComponent(chkLS3)
                .addGap(18, 18, 18)
                .addComponent(chkLsec3)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        activacion.setText("Activación");

        itemApagarTodas.setText("ApagarTodas");
        itemApagarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemApagarTodasActionPerformed(evt);
            }
        });
        activacion.add(itemApagarTodas);

        MenuEncender.setText("EncenderTodas");
        MenuEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEncenderActionPerformed(evt);
            }
        });
        activacion.add(MenuEncender);

        menuDia.setText("Dia");

        itemOficina1D.setText("Oficina 1");
        itemOficina1D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOficina1DActionPerformed(evt);
            }
        });
        menuDia.add(itemOficina1D);

        itemOficina2D.setText("Oficina 2");
        itemOficina2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOficina2DActionPerformed(evt);
            }
        });
        menuDia.add(itemOficina2D);

        itemOficina3D.setText("Oficina 3");
        itemOficina3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOficina3DActionPerformed(evt);
            }
        });
        menuDia.add(itemOficina3D);
        menuDia.add(jSeparator3);

        itemTodasD.setText("Todas");
        itemTodasD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTodasDActionPerformed(evt);
            }
        });
        menuDia.add(itemTodasD);

        activacion.add(menuDia);

        menuNoche.setText("Noche");

        itemOficina1N.setText("Oficina 1");
        itemOficina1N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOficina1NActionPerformed(evt);
            }
        });
        menuNoche.add(itemOficina1N);

        itemOficina2N.setText("Oficina 2");
        itemOficina2N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOficina2NActionPerformed(evt);
            }
        });
        menuNoche.add(itemOficina2N);

        itemOficina3N.setText("Oficina 3");
        itemOficina3N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOficina3NActionPerformed(evt);
            }
        });
        menuNoche.add(itemOficina3N);
        menuNoche.add(jSeparator1);

        itemTodasN.setText("Todas");
        itemTodasN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTodasNActionPerformed(evt);
            }
        });
        menuNoche.add(itemTodasN);

        activacion.add(menuNoche);
        activacion.add(jSeparator2);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        activacion.add(itemSalir);

        jMenuBar1.add(activacion);

        Info.setText("Info");

        itemPrincipales.setText("Principales");
        itemPrincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPrincipalesActionPerformed(evt);
            }
        });
        Info.add(itemPrincipales);

        itemSecundarias.setText("Secundarias");
        itemSecundarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSecundariasActionPerformed(evt);
            }
        });
        Info.add(itemSecundarias);

        itemSeguridad.setText("Seguridad");
        itemSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSeguridadActionPerformed(evt);
            }
        });
        Info.add(itemSeguridad);
        Info.add(jSeparator4);

        itemAcercade.setText("Acerca de...");
        itemAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercadeActionPerformed(evt);
            }
        });
        Info.add(itemAcercade);

        jMenuBar1.add(Info);

        jMenu1.setText("Herramientas");

        jMenuItem1.setText("Apagar Todas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Encender Todas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator5);

        jMenuItem3.setText("Modo Día");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Modo Nocturno");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator6);

        jMenuItem5.setText("Info - Principales");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Info - Secundarias");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Info - Seguridad");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panelOficina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelOficina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelOficina3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelOficina2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOficina1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOficina3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemApagarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemApagarTodasActionPerformed
        // TODO add your handling code here:
        this.chkLP1.setSelected(false);
        this.chkLS1.setSelected(false);
        this.chkLsec1.setSelected(false);
        this.chkLP2.setSelected(false);
        this.chkLS2.setSelected(false);
        this.chkLsec2.setSelected(false);
        this.chkLP3.setSelected(false);
        this.chkLS3.setSelected(false);
        this.chkLsec3.setSelected(false);     
    }//GEN-LAST:event_itemApagarTodasActionPerformed

    private void MenuEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEncenderActionPerformed
        // TODO add your handling code here:
        this.chkLP1.setSelected(true);
        this.chkLS1.setSelected(true);
        this.chkLsec1.setSelected(true);
        this.chkLP2.setSelected(true);
        this.chkLS2.setSelected(true);
        this.chkLsec2.setSelected(true);
        this.chkLP3.setSelected(true);
        this.chkLS3.setSelected(true);
        this.chkLsec3.setSelected(true);
    }//GEN-LAST:event_MenuEncenderActionPerformed

    private void itemOficina2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOficina2DActionPerformed
        // TODO add your handling code here:
        this.chkLP2.setSelected(true);
        this.chkLS2.setSelected(true);
        this.chkLsec2.setSelected(false);
    }//GEN-LAST:event_itemOficina2DActionPerformed

    private void itemOficina3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOficina3DActionPerformed
        // TODO add your handling code here:
        this.chkLP3.setSelected(true);
        this.chkLS3.setSelected(true);
        this.chkLsec3.setSelected(false);
    }//GEN-LAST:event_itemOficina3DActionPerformed

    private void itemOficina1DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOficina1DActionPerformed
        // TODO add your handling code here:
        this.chkLP1.setSelected(true);
        this.chkLS1.setSelected(true);
        this.chkLsec1.setSelected(false);
    }//GEN-LAST:event_itemOficina1DActionPerformed

    private void itemTodasDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTodasDActionPerformed
        // TODO add your handling code here:
        this.chkLP1.setSelected(true);
        this.chkLS1.setSelected(true);
        this.chkLsec1.setSelected(false);
        this.chkLP2.setSelected(true);
        this.chkLS2.setSelected(true);
        this.chkLsec2.setSelected(false);
        this.chkLP3.setSelected(true);
        this.chkLS3.setSelected(true);
        this.chkLsec3.setSelected(false);
    }//GEN-LAST:event_itemTodasDActionPerformed

    private void itemOficina1NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOficina1NActionPerformed
        // TODO add your handling code here:
        this.chkLP1.setSelected(false);
        this.chkLS1.setSelected(false);
        this.chkLsec1.setSelected(true);
    }//GEN-LAST:event_itemOficina1NActionPerformed

    private void itemOficina2NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOficina2NActionPerformed
        // TODO add your handling code here:
        this.chkLP2.setSelected(false);
        this.chkLS2.setSelected(false);
        this.chkLsec2.setSelected(true);
    }//GEN-LAST:event_itemOficina2NActionPerformed

    private void itemOficina3NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOficina3NActionPerformed
        // TODO add your handling code here:
        this.chkLP3.setSelected(false);
        this.chkLS3.setSelected(false);
        this.chkLsec3.setSelected(true);
    }//GEN-LAST:event_itemOficina3NActionPerformed

    private void itemTodasNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTodasNActionPerformed
        // TODO add your handling code here:
        this.chkLP1.setSelected(false);
        this.chkLS1.setSelected(false);
        this.chkLsec1.setSelected(true);
        this.chkLP2.setSelected(false);
        this.chkLS2.setSelected(false);
        this.chkLsec2.setSelected(true);
        this.chkLP3.setSelected(false);
        this.chkLS3.setSelected(false);
        this.chkLsec3.setSelected(true); 
    }//GEN-LAST:event_itemTodasNActionPerformed

    private void itemPrincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPrincipalesActionPerformed
        // TODO add your handling code here:
        int luces = 0;
        if (chkLP1.isSelected()){
            luces = luces + 1;
        } if (chkLP2.isSelected()){
            luces = luces + 1;
        } if (chkLP3.isSelected()){
            luces = luces + 1;
        }        
        JOptionPane.showMessageDialog(null, "Luces Principales Prendidas: "+ luces);        
    }//GEN-LAST:event_itemPrincipalesActionPerformed

    private void itemSecundariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSecundariasActionPerformed
        // TODO add your handling code here:
        int luces = 0;
        if (chkLS1.isSelected()){
            luces = luces + 1;
        }if (chkLS2.isSelected()){
            luces = luces + 1;
        }if (chkLS3.isSelected()){
            luces = luces + 1;
        }
        JOptionPane.showMessageDialog(null, "Luces Secundarias Prendidas: "+ luces);
    }//GEN-LAST:event_itemSecundariasActionPerformed

    private void itemSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSeguridadActionPerformed
        // TODO add your handling code here:
        int luces = 0;
        if (chkLsec1.isSelected()){
            luces = luces + 1;
        }  if (chkLsec2.isSelected()){
            luces = luces + 1;
        }  if (chkLsec3.isSelected()){
            luces = luces + 1;
        }        
        JOptionPane.showMessageDialog(null, "Luces de Seguridad Prendidas: "+ luces);
    }//GEN-LAST:event_itemSeguridadActionPerformed

    private void itemAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercadeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Programa: Control de Luces de un edificio \nProgramador: Edson Ruubén Juárez Lucas c:");
    }//GEN-LAST:event_itemAcercadeActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.chkLP1.setSelected(false);
        this.chkLS1.setSelected(false);
        this.chkLsec1.setSelected(false);
        this.chkLP2.setSelected(false);
        this.chkLS2.setSelected(false);
        this.chkLsec2.setSelected(false);
        this.chkLP3.setSelected(false);
        this.chkLS3.setSelected(false);
        this.chkLsec3.setSelected(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.chkLP1.setSelected(true);
        this.chkLS1.setSelected(true);
        this.chkLsec1.setSelected(true);
        this.chkLP2.setSelected(true);
        this.chkLS2.setSelected(true);
        this.chkLsec2.setSelected(true);
        this.chkLP3.setSelected(true);
        this.chkLS3.setSelected(true);
        this.chkLsec3.setSelected(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.chkLP1.setSelected(true);
        this.chkLS1.setSelected(true);
        this.chkLsec1.setSelected(false);
        this.chkLP2.setSelected(true);
        this.chkLS2.setSelected(true);
        this.chkLsec2.setSelected(false);
        this.chkLP3.setSelected(true);
        this.chkLS3.setSelected(true);
        this.chkLsec3.setSelected(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.chkLP1.setSelected(false);
        this.chkLS1.setSelected(false);
        this.chkLsec1.setSelected(true);
        this.chkLP2.setSelected(false);
        this.chkLS2.setSelected(false);
        this.chkLsec2.setSelected(true);
        this.chkLP3.setSelected(false);
        this.chkLS3.setSelected(false);
        this.chkLsec3.setSelected(true); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        int luces = 0;
        if (chkLP1.isSelected()){
            luces = luces + 1;
        } if (chkLP2.isSelected()){
            luces = luces + 1;
        } if (chkLP3.isSelected()){
            luces = luces + 1;
        }        
        JOptionPane.showMessageDialog(null, "Luces Principales Prendidas: "+ luces);
        JOptionPane.showMessageDialog(null, "Luces Principales Apagadas: "+ (3-luces));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        int luces = 0;
        if (chkLS1.isSelected()){
            luces = luces + 1;
        }if (chkLS2.isSelected()){
            luces = luces + 1;
        }if (chkLS3.isSelected()){
            luces = luces + 1;
        }
        JOptionPane.showMessageDialog(null, "Luces Secundarias Prendidas: "+ luces);
        JOptionPane.showMessageDialog(null, "Luces Secundrias Apagadas: "+ (3-luces));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        int luces = 0;
        if (chkLsec1.isSelected()){
            luces = luces + 1;
        }  if (chkLsec2.isSelected()){
            luces = luces + 1;
        }  if (chkLsec3.isSelected()){
            luces = luces + 1;
        }        
        JOptionPane.showMessageDialog(null, "Luces de Seguridad Prendidas: "+ luces);
        JOptionPane.showMessageDialog(null, "Luces de Seguridad Apagadas: "+ (3-luces));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ejercicio15().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Info;
    private javax.swing.JMenuItem MenuEncender;
    private javax.swing.JMenu activacion;
    private javax.swing.JCheckBox chkLP1;
    private javax.swing.JCheckBox chkLP2;
    private javax.swing.JCheckBox chkLP3;
    private javax.swing.JCheckBox chkLS1;
    private javax.swing.JCheckBox chkLS2;
    private javax.swing.JCheckBox chkLS3;
    private javax.swing.JCheckBox chkLsec1;
    private javax.swing.JCheckBox chkLsec2;
    private javax.swing.JCheckBox chkLsec3;
    private javax.swing.JMenuItem itemAcercade;
    private javax.swing.JMenuItem itemApagarTodas;
    private javax.swing.JMenuItem itemOficina1D;
    private javax.swing.JMenuItem itemOficina1N;
    private javax.swing.JMenuItem itemOficina2D;
    private javax.swing.JMenuItem itemOficina2N;
    private javax.swing.JMenuItem itemOficina3D;
    private javax.swing.JMenuItem itemOficina3N;
    private javax.swing.JMenuItem itemPrincipales;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemSecundarias;
    private javax.swing.JMenuItem itemSeguridad;
    private javax.swing.JMenuItem itemTodasD;
    private javax.swing.JMenuItem itemTodasN;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenu menuDia;
    private javax.swing.JMenu menuNoche;
    private javax.swing.JPanel panelOficina1;
    private javax.swing.JPanel panelOficina2;
    private javax.swing.JPanel panelOficina3;
    // End of variables declaration//GEN-END:variables
}
