/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicios567;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Ejercicio3 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio3
     */
    public Ejercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiCaso = new javax.swing.JLabel();
        etiSingular = new javax.swing.JLabel();
        etiPlural = new javax.swing.JLabel();
        etiNominativo = new javax.swing.JLabel();
        etiVocativo = new javax.swing.JLabel();
        etiAcusativo = new javax.swing.JLabel();
        etiGentitivo = new javax.swing.JLabel();
        etiDativo = new javax.swing.JLabel();
        atiAblativo = new javax.swing.JLabel();
        etiSNom = new javax.swing.JLabel();
        etiSVoc = new javax.swing.JLabel();
        etiSAcu = new javax.swing.JLabel();
        etiSGen = new javax.swing.JLabel();
        etiSDat = new javax.swing.JLabel();
        etiSAb = new javax.swing.JLabel();
        etiPNom = new javax.swing.JLabel();
        etiPVoc = new javax.swing.JLabel();
        etiPAcu = new javax.swing.JLabel();
        etiPGen = new javax.swing.JLabel();
        etiPDat = new javax.swing.JLabel();
        etiPAb = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        btnDeclinar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiCaso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiCaso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiCaso.setText("Caso");
        etiCaso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        etiSingular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiSingular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiSingular.setText("Singular");
        etiSingular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiSingular.setMaximumSize(new java.awt.Dimension(30, 17));
        etiSingular.setMinimumSize(new java.awt.Dimension(30, 17));

        etiPlural.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiPlural.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPlural.setText("Plural");
        etiPlural.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        etiNominativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiNominativo.setText("Nominativo");
        etiNominativo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        etiVocativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiVocativo.setText("Vocativo");
        etiVocativo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        etiAcusativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiAcusativo.setText("Acusativo");
        etiAcusativo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        etiGentitivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiGentitivo.setText("Gentitivo");
        etiGentitivo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        etiDativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiDativo.setText("Dativo");
        etiDativo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        atiAblativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        atiAblativo.setText("Ablativo");
        atiAblativo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        etiSNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiSNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiSNom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiSVoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiSVoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiSVoc.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiSAcu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiSAcu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiSAcu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiSGen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiSGen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiSGen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiSDat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiSDat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiSDat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiSAb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiSAb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiSAb.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiPNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiPNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPNom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiPVoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiPVoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPVoc.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiPAcu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiPAcu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPAcu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiPGen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiPGen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPGen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiPDat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiPDat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPDat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiPAb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiPAb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPAb.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPalabra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPalabra.setBorder(javax.swing.BorderFactory.createTitledBorder("Escriba la palabra a Declinar:"));

        btnDeclinar.setText("Declinar");
        btnDeclinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclinarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiDativo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiGentitivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiAcusativo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiVocativo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiNominativo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(etiCaso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atiAblativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiSingular, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(etiSNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiSVoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiSAcu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiSGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiSDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiSAb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiPlural, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(etiPNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiPVoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiPAcu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiPGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiPDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiPAb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnDeclinar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiSingular, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiPlural, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiPNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiSNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiNominativo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiPVoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiSVoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiVocativo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etiPAcu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etiSAcu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etiAcusativo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiPGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiSGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiGentitivo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnDeclinar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiPDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiSDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiDativo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(atiAblativo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(etiSAb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiPAb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeclinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclinarActionPerformed
        // TODO add your handling code here:
        String latin0 = txtPalabra.getText();
        String latin = latin0.toLowerCase();        
        if (latin.endsWith("a")) {
        etiSNom.setText(latin);
        etiSVoc.setText(latin);
        etiSAcu.setText(latin +"m");
        etiSGen.setText(latin +"e");
        etiSDat.setText(latin +"e");
        etiSAb.setText(latin );
        etiPNom.setText(latin+ "e");
        etiPVoc.setText(latin+ "e");
        etiPAcu.setText(latin+"s");
        etiPGen.setText(latin+"rum");
        String a = latin.substring(0,latin.length()-1);
        etiPDat.setText(a+ "is");
        etiPAb.setText(a+"is");
        } else {
            JOptionPane.showMessageDialog(null, "Error, la palabra no termina con a");
        }   
     
    }//GEN-LAST:event_btnDeclinarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atiAblativo;
    private javax.swing.JButton btnDeclinar;
    private javax.swing.JLabel etiAcusativo;
    private javax.swing.JLabel etiCaso;
    private javax.swing.JLabel etiDativo;
    private javax.swing.JLabel etiGentitivo;
    private javax.swing.JLabel etiNominativo;
    private javax.swing.JLabel etiPAb;
    private javax.swing.JLabel etiPAcu;
    private javax.swing.JLabel etiPDat;
    private javax.swing.JLabel etiPGen;
    private javax.swing.JLabel etiPNom;
    private javax.swing.JLabel etiPVoc;
    private javax.swing.JLabel etiPlural;
    private javax.swing.JLabel etiSAb;
    private javax.swing.JLabel etiSAcu;
    private javax.swing.JLabel etiSDat;
    private javax.swing.JLabel etiSGen;
    private javax.swing.JLabel etiSNom;
    private javax.swing.JLabel etiSVoc;
    private javax.swing.JLabel etiSingular;
    private javax.swing.JLabel etiVocativo;
    private javax.swing.JTextField txtPalabra;
    // End of variables declaration//GEN-END:variables
}
