/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicios567;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
    }
    
    private int cuentas(String sPalabra, char a){
        int contador=0;        
        for(int x=0;x<sPalabra.length();x++) {
         if ((sPalabra.charAt(x)==a)){
             contador++;
             }
         }
        return contador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFrase = new javax.swing.JTextField();
        btnAnalizar = new javax.swing.JButton();
        etiVocalA = new javax.swing.JLabel();
        etiVocalE = new javax.swing.JLabel();
        etiVocalI = new javax.swing.JLabel();
        etiVocalO = new javax.swing.JLabel();
        etiVocalU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFrase.setBorder(javax.swing.BorderFactory.createTitledBorder("Escriba una frase:"));

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        etiVocalA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etiVocalA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiVocalA.setBorder(javax.swing.BorderFactory.createTitledBorder("# de repeticiones de A"));

        etiVocalE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etiVocalE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiVocalE.setBorder(javax.swing.BorderFactory.createTitledBorder("# de repeticiones de E"));

        etiVocalI.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etiVocalI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiVocalI.setBorder(javax.swing.BorderFactory.createTitledBorder("# de repeticiones de I"));

        etiVocalO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etiVocalO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiVocalO.setBorder(javax.swing.BorderFactory.createTitledBorder("# de repeticiones de O"));

        etiVocalU.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etiVocalU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiVocalU.setBorder(javax.swing.BorderFactory.createTitledBorder("# de repeticiones de U"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFrase)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiVocalA, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(etiVocalI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiVocalO, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(etiVocalE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnAnalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(etiVocalU, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnalizar)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiVocalE, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiVocalI, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(etiVocalO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(etiVocalA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiVocalU, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
        String frase = txtFrase.getText();
        String frase2= frase.toLowerCase();
        if (txtFrase.getText()!=null||frase!=""||txtFrase.getText()!=""||frase!=null||!frase.equals("")||!frase.equals(null)) {
        int a =cuentas(frase2,'a');
        int e =cuentas(frase2,'e');
        int i =cuentas(frase2,'i');
        int o =cuentas(frase2,'o');
        int u =cuentas(frase2,'u');
        etiVocalA.setText(""+ a);
        etiVocalE.setText(""+ e);
        etiVocalI.setText(""+ i);
        etiVocalO.setText(""+ o);
        etiVocalU.setText(""+ u);
       
        } else if (txtFrase.getText()==null||frase==""||txtFrase.getText()==""||frase==null||frase.equals("")||frase.equals(null)){             
         JOptionPane.showMessageDialog(null, "Error, no hay frase la cual analizar");        
        }             
    }//GEN-LAST:event_btnAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JLabel etiVocalA;
    private javax.swing.JLabel etiVocalE;
    private javax.swing.JLabel etiVocalI;
    private javax.swing.JLabel etiVocalO;
    private javax.swing.JLabel etiVocalU;
    private javax.swing.JTextField txtFrase;
    // End of variables declaration//GEN-END:variables
}
