/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edjuarez.ejercicios21_24;

import java.awt.Toolkit;

/**
 *
 * @author Usuario
 */
public class Ejercicio21 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio21
     */
    public Ejercicio21() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogCosteInstalacion = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcopiasSimples = new javax.swing.JTextField();
        txtcopiasCompletas = new javax.swing.JTextField();
        btonoAceptarCI = new javax.swing.JButton();
        botonCancelarCI = new javax.swing.JButton();
        dialogCosteFormacion = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAlumnos = new javax.swing.JTextField();
        txtHrs = new javax.swing.JTextField();
        botonAceptarCF = new javax.swing.JButton();
        botonCancelarCF = new javax.swing.JButton();
        dialogCosteMantenimiento = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        radioAnual = new javax.swing.JRadioButton();
        radioSemestral = new javax.swing.JRadioButton();
        radioFuncionam = new javax.swing.JRadioButton();
        botonAceptarCM = new javax.swing.JButton();
        botonCancelarCM = new javax.swing.JButton();
        groupOM = new javax.swing.ButtonGroup();
        dialogAyuda = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        botonCancelarAyuda = new javax.swing.JButton();
        dialogPres = new javax.swing.JDialog();
        botonCerrarPres = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCosteI = new javax.swing.JTextField();
        txtCosteF = new javax.swing.JTextField();
        txtCosteM = new javax.swing.JTextField();
        etiTotalT = new javax.swing.JLabel();
        botonCI = new javax.swing.JButton();
        botonFormacion = new javax.swing.JButton();
        botonMant = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        botonAsk = new javax.swing.JButton();

        jLabel6.setText("Versión Simplificada");

        jLabel7.setText("No. de Copias:");

        jLabel8.setText("Versión Completa");

        jLabel9.setText("No. de Copias:");

        btonoAceptarCI.setText("Aceptar");
        btonoAceptarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonoAceptarCIActionPerformed(evt);
            }
        });

        botonCancelarCI.setText("Cancelar");
        botonCancelarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarCIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogCosteInstalacionLayout = new javax.swing.GroupLayout(dialogCosteInstalacion.getContentPane());
        dialogCosteInstalacion.getContentPane().setLayout(dialogCosteInstalacionLayout);
        dialogCosteInstalacionLayout.setHorizontalGroup(
            dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogCosteInstalacionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCosteInstalacionLayout.createSequentialGroup()
                        .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(42, 42, 42)
                        .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcopiasCompletas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcopiasSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btonoAceptarCI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonCancelarCI, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        dialogCosteInstalacionLayout.setVerticalGroup(
            dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteInstalacionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtcopiasSimples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btonoAceptarCI))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCosteInstalacionLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(dialogCosteInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtcopiasCompletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialogCosteInstalacionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelarCI)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel5.setText("Número de Alumnos: ");

        jLabel10.setText("Número de Horas:");

        botonAceptarCF.setText("Aceptar");
        botonAceptarCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarCFActionPerformed(evt);
            }
        });

        botonCancelarCF.setText("Cancelar");
        botonCancelarCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarCFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogCosteFormacionLayout = new javax.swing.GroupLayout(dialogCosteFormacion.getContentPane());
        dialogCosteFormacion.getContentPane().setLayout(dialogCosteFormacionLayout);
        dialogCosteFormacionLayout.setHorizontalGroup(
            dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteFormacionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAceptarCF)
                    .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel10)))
                .addGap(45, 45, 45)
                .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtAlumnos)
                        .addComponent(txtHrs, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                    .addComponent(botonCancelarCF))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        dialogCosteFormacionLayout.setVerticalGroup(
            dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteFormacionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(dialogCosteFormacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptarCF)
                    .addComponent(botonCancelarCF))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de Mantenimiento"));

        radioAnual.setText("Anual");

        radioSemestral.setText("Semestral");

        radioFuncionam.setText("Puesta en Funcionamiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioFuncionam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioSemestral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioAnual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(radioAnual)
                .addGap(18, 18, 18)
                .addComponent(radioSemestral)
                .addGap(18, 18, 18)
                .addComponent(radioFuncionam)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        botonAceptarCM.setText("Aceptar");
        botonAceptarCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarCMActionPerformed(evt);
            }
        });

        botonCancelarCM.setText("Cancelar");
        botonCancelarCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarCMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogCosteMantenimientoLayout = new javax.swing.GroupLayout(dialogCosteMantenimiento.getContentPane());
        dialogCosteMantenimiento.getContentPane().setLayout(dialogCosteMantenimientoLayout);
        dialogCosteMantenimientoLayout.setHorizontalGroup(
            dialogCosteMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteMantenimientoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(dialogCosteMantenimientoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(botonAceptarCM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCancelarCM)
                .addGap(41, 41, 41))
        );
        dialogCosteMantenimientoLayout.setVerticalGroup(
            dialogCosteMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCosteMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogCosteMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptarCM)
                    .addComponent(botonCancelarCM))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTextPane1.setText("Cálculo de Costes\n\nHerramienta de apoyo para el cálculo de costes de implementación de Software.\n\n-Use el cuadro de texto de Coste de Instalación para introducir directamente \nel coste de instalación del software, o bien pulse el botón asociado para calcular\ndicho coste.\n\n-Use el cuadro de texto Coste de Formación o su botón asociado para introducir\n el coste de formación de los empleados.\n\n-Use el cuadro de texto Coste de Mantenimiento o su botón asociado para\n introducir el coste de mantenimiento del software.\n");
        jScrollPane1.setViewportView(jTextPane1);

        botonCancelarAyuda.setText("Cancelar");
        botonCancelarAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogAyudaLayout = new javax.swing.GroupLayout(dialogAyuda.getContentPane());
        dialogAyuda.getContentPane().setLayout(dialogAyudaLayout);
        dialogAyudaLayout.setHorizontalGroup(
            dialogAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAyudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(dialogAyudaLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(botonCancelarAyuda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogAyudaLayout.setVerticalGroup(
            dialogAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAyudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCancelarAyuda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogPres.setAlwaysOnTop(true);
        dialogPres.setIconImage(null);
        dialogPres.setUndecorated(true);
        dialogPres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dialogPresMouseClicked(evt);
            }
        });

        botonCerrarPres.setText("Cerrar");
        botonCerrarPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarPresActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Bienvenido al programa de Administración de Instalación de Software");

        jLabel12.setText("Programado por: JuarezL Edson Rubén");

        jLabel13.setText("Instituto Tecnológico de Oaxaca, México (2020)");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\d41bc7b4dd4240b8fb4237a0b03c1345.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setAutoscrolls(true);
        jLabel14.setDisabledIcon(null);
        jLabel14.setMaximumSize(new java.awt.Dimension(231, 188));
        jLabel14.setMinimumSize(new java.awt.Dimension(231, 138));
        jLabel14.setPreferredSize(new java.awt.Dimension(231, 188));

        javax.swing.GroupLayout dialogPresLayout = new javax.swing.GroupLayout(dialogPres.getContentPane());
        dialogPres.getContentPane().setLayout(dialogPresLayout);
        dialogPresLayout.setHorizontalGroup(
            dialogPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPresLayout.createSequentialGroup()
                .addGroup(dialogPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogPresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dialogPresLayout.createSequentialGroup()
                        .addGroup(dialogPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogPresLayout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(botonCerrarPres))
                            .addGroup(dialogPresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(dialogPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        dialogPresLayout.setVerticalGroup(
            dialogPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dialogPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogPresLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(dialogPresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(botonCerrarPres)
                .addGap(29, 29, 29))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ed Juarez EJ21");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Coste de Instalación");

        jLabel2.setText("Coste de Formación");

        jLabel3.setText("Coste de Mantenimiento");

        jLabel4.setText("Total");

        txtCosteI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCosteI.setText("0");

        txtCosteF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCosteF.setText("0");

        txtCosteM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCosteM.setText("0");

        etiTotalT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonCI.setText("...");
        botonCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCIActionPerformed(evt);
            }
        });

        botonFormacion.setText("...");
        botonFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFormacionActionPerformed(evt);
            }
        });

        botonMant.setText("...");
        botonMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMantActionPerformed(evt);
            }
        });

        jButton4.setText("Calcular");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        botonAsk.setText("?");
        botonAsk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCosteI, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCosteF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonFormacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCosteM, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiTotalT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMant, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(botonAsk)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCosteI, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCI)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonAsk)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCosteF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFormacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCosteM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMant))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiTotalT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarCIActionPerformed
        // TODO add your handling code here:
        dialogCosteInstalacion.dispose();
    }//GEN-LAST:event_botonCancelarCIActionPerformed

    private void btonoAceptarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonoAceptarCIActionPerformed
        // TODO add your handling code here:
        int copiasS= Integer.parseInt(txtcopiasSimples.getText());
        int copiasC= Integer.parseInt(txtcopiasCompletas.getText());
        int totalS= 120*copiasS;
        int totalC= 180*copiasC;
        int tcosteI= totalS + totalC;
        txtCosteI.setText(""+ tcosteI);
    }//GEN-LAST:event_btonoAceptarCIActionPerformed

    private void botonCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCIActionPerformed
        // TODO add your handling code here:
        dialogCosteInstalacion.setSize(390,250);
        dialogCosteInstalacion.setLocation(100,100);
        dialogCosteInstalacion.setVisible(true);
    }//GEN-LAST:event_botonCIActionPerformed

    private void botonCancelarCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarCFActionPerformed
        // TODO add your handling code here:
        dialogCosteFormacion.dispose();
    }//GEN-LAST:event_botonCancelarCFActionPerformed

    private void botonAceptarCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarCFActionPerformed
        // TODO add your handling code here:
        int alumnos = Integer.parseInt(txtAlumnos.getText());
        int hrs = Integer.parseInt(txtHrs.getText());
        int totalCF = (alumnos * hrs) * 10;
        txtCosteF.setText(""+ totalCF);
    }//GEN-LAST:event_botonAceptarCFActionPerformed

    private void botonFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFormacionActionPerformed
        // TODO add your handling code here:
        dialogCosteFormacion.setSize(300,220);
        dialogCosteFormacion.setLocation(100,100);
        dialogCosteFormacion.setVisible(true);
    }//GEN-LAST:event_botonFormacionActionPerformed

    private void botonCancelarCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarCMActionPerformed
        // TODO add your handling code here
        dialogCosteMantenimiento.dispose();
    }//GEN-LAST:event_botonCancelarCMActionPerformed

    private void botonAceptarCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarCMActionPerformed
        // TODO add your handling code here:
        if(radioAnual.isSelected()){
            txtCosteM.setText(""+600);
        }
        if(radioSemestral.isSelected()){
            txtCosteM.setText(""+350);
        }
        if(radioFuncionam.isSelected()){
            txtCosteM.setText(""+200);
        }
        dialogCosteMantenimiento.dispose();
    }//GEN-LAST:event_botonAceptarCMActionPerformed

    private void botonAskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAskActionPerformed
        // TODO add your handling code here:
        dialogAyuda.setSize(450, 420);
        dialogAyuda.setLocation(100,100);
        dialogAyuda.setVisible(true);
    }//GEN-LAST:event_botonAskActionPerformed

    private void botonCancelarAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarAyudaActionPerformed
        // TODO add your handling code here:
        dialogAyuda.dispose();
    }//GEN-LAST:event_botonCancelarAyudaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here: 522, 351
        dialogPres.setSize(522, 351);
        int x=(int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth()/2 -  dialogPres.getWidth()/2);
        int y=(int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight()/2 -  dialogPres.getHeight()/2);
        dialogPres.setLocation(x,y);
        dialogPres.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void botonCerrarPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarPresActionPerformed
        // TODO add your handling code here:
        dialogPres.dispose();
    }//GEN-LAST:event_botonCerrarPresActionPerformed

    private void dialogPresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dialogPresMouseClicked
        // TODO add your handling code here:
        dialogPres.dispose();
    }//GEN-LAST:event_dialogPresMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here: 412, 267        
        int T1 = Integer.parseInt(txtCosteI.getText());
        int T2 = Integer.parseInt(txtCosteF.getText());
        int T3 = Integer.parseInt(txtCosteM.getText());
        int TotalT = T1+T2+T3;
        etiTotalT.setText("$"+TotalT);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void botonMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMantActionPerformed
        // TODO add your handling code here:
        dialogCosteMantenimiento.setSize(340,270);
        dialogCosteMantenimiento.setLocation(100,100);
        dialogCosteMantenimiento.setVisible(true);
    }//GEN-LAST:event_botonMantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio21().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarCF;
    private javax.swing.JButton botonAceptarCM;
    private javax.swing.JButton botonAsk;
    private javax.swing.JButton botonCI;
    private javax.swing.JButton botonCancelarAyuda;
    private javax.swing.JButton botonCancelarCF;
    private javax.swing.JButton botonCancelarCI;
    private javax.swing.JButton botonCancelarCM;
    private javax.swing.JButton botonCerrarPres;
    private javax.swing.JButton botonFormacion;
    private javax.swing.JButton botonMant;
    private javax.swing.JButton btonoAceptarCI;
    private javax.swing.JDialog dialogAyuda;
    private javax.swing.JDialog dialogCosteFormacion;
    private javax.swing.JDialog dialogCosteInstalacion;
    private javax.swing.JDialog dialogCosteMantenimiento;
    private javax.swing.JDialog dialogPres;
    private javax.swing.JLabel etiTotalT;
    private javax.swing.ButtonGroup groupOM;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JRadioButton radioAnual;
    private javax.swing.JRadioButton radioFuncionam;
    private javax.swing.JRadioButton radioSemestral;
    private javax.swing.JTextField txtAlumnos;
    private javax.swing.JTextField txtCosteF;
    private javax.swing.JTextField txtCosteI;
    private javax.swing.JTextField txtCosteM;
    private javax.swing.JTextField txtHrs;
    private javax.swing.JTextField txtcopiasCompletas;
    private javax.swing.JTextField txtcopiasSimples;
    // End of variables declaration//GEN-END:variables
}
