/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicios3y4topicos;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Ejercicio5 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio5
     */
    public Ejercicio5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCadena = new javax.swing.JTextField();
        btnAnaliza = new javax.swing.JButton();
        txtSubcadena = new javax.swing.JTextField();
        etiInicial = new javax.swing.JLabel();
        etiFinal = new javax.swing.JLabel();
        txtAnterior = new javax.swing.JLabel();
        txtPosterior = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCadena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCadena.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadena"));

        btnAnaliza.setText("Analizar");
        btnAnaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizaActionPerformed(evt);
            }
        });

        txtSubcadena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubcadena.setBorder(javax.swing.BorderFactory.createTitledBorder("SubCadena"));

        etiInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiInicial.setBorder(javax.swing.BorderFactory.createTitledBorder("Posición inicial"));

        etiFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiFinal.setBorder(javax.swing.BorderFactory.createTitledBorder("Posición final"));

        txtAnterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnterior.setBorder(javax.swing.BorderFactory.createTitledBorder("Texto Anterior"));

        txtPosterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPosterior.setBorder(javax.swing.BorderFactory.createTitledBorder("Texto Posterior"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(btnAnaliza))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(etiInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(etiFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCadena)
                            .addComponent(txtSubcadena)
                            .addComponent(txtPosterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubcadena, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnaliza)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(etiInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPosterior, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizaActionPerformed
        // TODO add your handling code here:
        String frase = txtCadena.getText();
        String palabra = txtSubcadena.getText();
        int ini = frase.indexOf(palabra);
        int fin = frase.lastIndexOf(palabra);
        if (ini==-1) {
            JOptionPane.showMessageDialog(null, "Error, no hay tal palabra");
        etiInicial.setText("");
        etiFinal.setText("");
        txtAnterior.setText("");
        txtPosterior.setText("");
        } else {
        etiInicial.setText(""+ini);
        etiFinal.setText(""+ fin);
        txtAnterior.setText(""+ frase.substring(0, ini));
        txtPosterior.setText(""+frase.substring(fin+palabra.length(), frase.length()));        
        }       
    }//GEN-LAST:event_btnAnalizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnaliza;
    private javax.swing.JLabel etiFinal;
    private javax.swing.JLabel etiInicial;
    private javax.swing.JLabel txtAnterior;
    private javax.swing.JTextField txtCadena;
    private javax.swing.JLabel txtPosterior;
    private javax.swing.JTextField txtSubcadena;
    // End of variables declaration//GEN-END:variables
}
