/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edjuarez.ejercicio11.y13;

/**
 *
 * @author Usuario
 */
public class Ejercicio12 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio12
     */
    public Ejercicio12() {
        initComponents();
    }
    
    private void calculos(){
        int x= SliderLitros.getValue();
        int y = sliderDet.getValue();
        int z = sliderdensidad.getValue();
        //Litros de agua = 2 * Litros a Fabricar + Calidad / Densidad
        int awa = (2*x)+y/z;
        //Sales = (Calidad * Litros a Fabricar) / (100 * Densidad)
        double sal = (y*x)/(100*z);        
        awa1.setText(awa+" lts.");         
        sales1.setText(sal+ "kg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SliderLitros = new javax.swing.JSlider();
        sliderDet = new javax.swing.JSlider();
        sliderdensidad = new javax.swing.JSlider();
        eti1 = new javax.swing.JLabel();
        eti2 = new javax.swing.JLabel();
        eti3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        awa1 = new javax.swing.JLabel();
        sales1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SliderLitros.setMajorTickSpacing(10);
        SliderLitros.setMinorTickSpacing(5);
        SliderLitros.setPaintLabels(true);
        SliderLitros.setPaintTicks(true);
        SliderLitros.setSnapToTicks(true);
        SliderLitros.setBorder(javax.swing.BorderFactory.createTitledBorder("Litros a fabricar"));
        SliderLitros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SliderLitros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderLitrosStateChanged(evt);
            }
        });

        sliderDet.setMajorTickSpacing(1);
        sliderDet.setMaximum(10);
        sliderDet.setMinorTickSpacing(1);
        sliderDet.setPaintLabels(true);
        sliderDet.setPaintTicks(true);
        sliderDet.setValue(5);
        sliderDet.setBorder(javax.swing.BorderFactory.createTitledBorder("Calidad del Detergente"));
        sliderDet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderDetStateChanged(evt);
            }
        });

        sliderdensidad.setMajorTickSpacing(10);
        sliderdensidad.setMaximum(200);
        sliderdensidad.setMinimum(50);
        sliderdensidad.setMinorTickSpacing(5);
        sliderdensidad.setPaintLabels(true);
        sliderdensidad.setPaintTicks(true);
        sliderdensidad.setValue(100);
        sliderdensidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Densidad deseada"));
        sliderdensidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderdensidadStateChanged(evt);
            }
        });

        eti1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        eti1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        eti2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        eti2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        eti3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        eti3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Totales"));

        awa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        awa1.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Agua:"));

        sales1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sales1.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Sales:"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sales1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(awa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(awa1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sales1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SliderLitros, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                        .addComponent(sliderDet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sliderdensidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eti1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eti2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(eti3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(SliderLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(eti1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(sliderDet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(eti2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(sliderdensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(eti3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SliderLitrosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderLitrosStateChanged
        // TODO add your handling code here:
                eti1.setText(SliderLitros.getValue() + "");
                calculos();
    }//GEN-LAST:event_SliderLitrosStateChanged

    private void sliderDetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderDetStateChanged
        // TODO add your handling code here:
        eti2.setText(sliderDet.getValue() + "");
        calculos();
    }//GEN-LAST:event_sliderDetStateChanged

    private void sliderdensidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderdensidadStateChanged
        // TODO add your handling code here:
        eti3.setText(sliderdensidad.getValue() + "");
        calculos();
    }//GEN-LAST:event_sliderdensidadStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider SliderLitros;
    private javax.swing.JLabel awa1;
    private javax.swing.JLabel eti1;
    private javax.swing.JLabel eti2;
    private javax.swing.JLabel eti3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sales1;
    private javax.swing.JSlider sliderDet;
    private javax.swing.JSlider sliderdensidad;
    // End of variables declaration//GEN-END:variables
}
